name: CI pipeline
on:
  push:
    branches:
      - feature/dac
  pull_request:
    branches:
      - feature/dac
jobs:
  vale:
    name: Docs checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          version: 3.12.0
          files: docs
          fail_on_error: true
          filter_mode: nofilter
          reporter: local
